### ISSUE TITLE
[Bug]: 'page.waitForTimeout' not working in Puppeteer 22.7.1

### ISSUE THREAD

**Issue by YAnubhavChetan** [puppeteer/puppeteer#12333]
### Minimal, reproducible example

```TypeScript
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: "new" }); 
  const page = await browser.newPage();

  try {
    await page.goto('https://www.google.com/');
    console.log('Navigated to Google website.');

    // Wait for 2 seconds using page.waitForTimeout
    await page.waitForTimeout(2000);
    console.log('Waited for 2 seconds using page.waitForTimeout');

  } catch (error) {
    console.error('Error occurred:', error);
  } finally {
    await browser.close();
  }
})();
```

### Error string

Error occurred: TypeError: page.waitForTimeout is not a function

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I was trying to use _waitForTimeout_ function in my nodejs puppeteer program, but it shows **TypeError** for the past two days.
I have updated my puppeteer version from **21.9.0 to 22.7.1** before running the program. I run the program several time afterwards but it gets the same TypeError.

So I downgrade my puppeteer version to 21.9.0 and run the program afterwards and this time I don't find any error, which lead me to think that its definitely a bug in this new version. 

Then I created this simple puppeteer code to demonstrate the error i am encountering with the latest version.

### Expectation

The code working is simple as you can see it yourself.

When run, this code goes to google website and then wait for two seconds and close it.

### Reality

But it shows the **TypeError** on the **waitForTimeout** function.

### Puppeteer version

22.7.1

### Node version

20.11.1

### Package manager

npm

### Package manager version

10.5.2

### Operating system

Windows

**Comment by OrKoN** [comment]
waitForTimeout is deprecated and removed in v22 (https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v22.0.0)
