### ISSUE TITLE
[Bug]: Cannot find module 'chromium-bidi/protocol/protocol.js' or its corresponding type declarations

### ISSUE THREAD

**Issue by Mitesh1711** [puppeteer/puppeteer#13833]
### Minimal, reproducible example

```TypeScript
npm i puppeteer in nodejs typescript project installs ^24.8.0, when building the project,

I get this error: 
node_modules/puppeteer/lib/types.d.ts:8:25 - error TS2307: Cannot find module 'chromium-bidi/protocol/protocol.js' or its corresponding type declarations.

8 import { Session } from 'chromium-bidi/protocol/protocol.js';
```

### Expectation

It should build the project without any error with latest version.

### Reality

It breaks the build

### Puppeteer configuration file (if used)

```TypeScript

```

### Puppeteer version

24.8.0

### Node version

22

### Package manager

npm

### Package manager version

10.9.2

### Operating system

Windows

**Comment by OrKoN** [comment]
What's your TypeScript config? I am not able to reproduce with skipLibCheck=true or skipLibCheck=false + moduleResolution=node.

**Comment by marcomontalbano** [comment]
Hi @OrKoN, here you can find a repro.

https://stackblitz.com/edit/vitejs-vite-5j7xfdcz?file=package.json

I've the same issue on a project that is using `moduleResolution=node` with `skipLibCheck=false`.
It worked fine on `v24.7.2`.

To create the repro I just:
- Install typescript
- Create tsconfig.json with `tsc --init`
- Install puppeteer
- Import puppeteer in an `index.ts` file

**Comment by OrKoN** [comment]
Thanks @marcomontalbano the error message in your repro is: `There are types at '/home/projects/vitejs-vite-5j7xfdcz/node_modules/chromium-bidi/lib/esm/protocol/protocol.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.` Are you not targeting Node?

@Lightning00Blade PTAL I think something changed in chromium-bidi that prevents tsc from finding types without Node resolution.

**Comment by OrKoN** [comment]
@connorjclark the module resolution node is outdated and it is for Node versions older than v10 (https://www.typescriptlang.org/tsconfig/#moduleResolution).

**Comment by OrKoN** [comment]
I'd suggest using NodeNext or at least Node18/node16. Note that Node 18 also reached end-of-life and we will probably drop its support soon (and that means some TypeScript options targeting older Node versions might not work as well).

**Comment by kirillvakalov** [comment]
Error is present for me with `NodeNext` module resolution

**Comment by OrKoN** [comment]
Could you please provide your tsc config?

TypeScript 5.8.3 the following builds fine.

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "NodeNext",
    "moduleResolution": "nodenext",
    "strict": true,
    "skipLibCheck": false
  }
}
```

**Comment by laureProthais** [comment]
Same issue for me. My tsc config : 
`
 "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": false,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2022"
    ],
    "moduleResolution": "bundler",
    "module": "esnext",
    "target": "es2022",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "jsx": "react",
    "jsxFactory": "h",
    "jsxFragmentFactory": "h.Fragment"
  },
`

For information, it's auto-generate by `npm create stencil`

**Comment by OrKoN** [comment]
> Same issue for me. My tsc config :
> 
>  "compilerOptions": {
>     "allowSyntheticDefaultImports": true,
>     "allowUnreachableCode": false,
>     "declaration": false,
>     "experimentalDecorators": true,
>     "lib": [
>       "dom",
>       "es2022"
>     ],
>     "moduleResolution": "bundler",
>     "module": "esnext",
>     "target": "es2022",
>     "noUnusedLocals": true,
>     "noUnusedParameters": true,
>     "jsx": "react",
>     "jsxFactory": "h",
>     "jsxFragmentFactory": "h.Fragment"
>   },
> For information, it's auto-generate by `npm create stencil`

I am not able to reproduce with this config (TypeScript 5.8.3)

**Comment by louis-lau** [comment]
Same here with commonjs in my nestjs app:

```json
{
	"compilerOptions": {
		"module": "commonjs",
		"declaration": true,
		"removeComments": true,
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"allowSyntheticDefaultImports": true,
		"target": "es2020",
		"sourceMap": true,
		"outDir": "./dist",
		"baseUrl": "./",
		"incremental": true
	},
	"ts-node": {
		"require": ["tsconfig-paths/register"]
	}
}

```

Manually adding the type definitions to my tsconfig seems to "fix" it. But since this seems like a hack, I'll stay on the older version for now

```diff
diff --git a/tsconfig.json b/tsconfig.json
index c99df1095..68893dd84 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -10,7 +10,10 @@
 		"sourceMap": true,
 		"outDir": "./dist",
 		"baseUrl": "./",
-		"incremental": true
+		"incremental": true,
+		"paths": {
+			"chromium-bidi/protocol/protocol.js": ["node_modules/chromium-bidi/lib/esm/protocol/protocol.d.ts"]
+		}
 	},
 	"ts-node": {
 		"require": ["tsconfig-paths/register"]

```

**Comment by OrKoN** [comment]
> "module": "commonjs",
> 		"declaration": true,
> 		"removeComments": true,
> 		"emitDecoratorMetadata": true,
> 		"experimentalDecorators": true,
> 		"allowSyntheticDefaultImports": true,
> 		"target": "es2020",
> 		"sourceMap": true,
> 		"outDir": "./dist",
> 		"baseUrl": "./",
> 		"incremental": true

Setting `"moduleResolution": "nodenext"` would fix the issue (I am able to reproduce the issue with your config).

**Comment by marcomontalbano** [comment]
I just tested with the latest `puppeteer@24.8.1` and now everything is working properly without additional changes in my codebase.
