### ISSUE TITLE
[Bug]: Cannot find module '.../node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs'

### ISSUE THREAD

**Issue by calixteman** [puppeteer/puppeteer#11298]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer";

const options = {
    product: "chrome",
    protocol: "webDriverBiDi",
    headless: false,
    defaultViewport: null,
    ignoreDefaultArgs: ["--disable-extensions"],
};

const browser = await puppeteer.launch(options);
```

and the package.json
```json
{
  "name": "plop",
  "type": "module",
  "devDependencies": {
    "puppeteer": "^21.5.0"
  },
  "engines": {
    "node": ">=18"
  }
}
```

### Error string

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/tmp/foo/node_modules/puppeteer-core/lib/esm/third_party/rxjs/rxjs' imported from /tmp/foo/node_modules/puppeteer-core/lib/esm/puppeteer/bidi/lifecycle.js

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

We want to use bidi protocol in pdf.js with puppeteer 21.5.0 and we got this error.
The above code is a minimal test case.

### Expectation

To run without any errors.

### Reality

An error.

### Puppeteer version

21.5.0

### Node version

18.15.0

### Package manager

npm

### Package manager version

9.5.0

### Operating system

Windows

**Comment by whimboo** [comment]
@Lightning00Blade can you please have a look? It seems that with https://github.com/puppeteer/puppeteer/commit/443ee99a8dc2bdc1a25391c3f4c696eae14c6b4c not all issues with the rxjs import have been fixed.

This is a regression in the 21.5.0 release and everything was working fine with BiDi in 21.4.1.
