### ISSUE TITLE
[Bug]: ERR! cb.apply is not a function

### ISSUE THREAD

**Issue by akalankasakalasooriya** [puppeteer/puppeteer#11443]
### Steps to reproduce

npx -v is 10.2.2
npm -v is 9.6.3
node -v is v19.9.0

```
npx @puppeteer/browsers install chrome@stable
```

### Expected results

Install chrome stable version

### Actual results

```
npm ERR! cb.apply is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/akalanka/.npm/_logs/2023-11-24T16_32_49_632Z-debug.log
```
Complete log of this run
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/akalanka/.nvm/versions/node/v19.9.0/bin/node',
1 verbose cli   '/home/akalanka/.nvm/versions/node/v19.9.0/lib/node_modules/npx/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@puppeteer/browsers@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/home/akalanka/.npm/_npx/5741',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@5.1.0
3 info using node@v19.9.0
4 verbose npm-session 2c3068343071939b
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/@puppeteer%2fbrowsers 24ms (from cache)
8 silly pacote tag manifest for @puppeteer/browsers@latest fetched in 42ms
9 verbose stack TypeError: cb.apply is not a function
9 verbose stack     at /home/akalanka/.nvm/versions/node/v19.9.0/lib/node_modules/npx/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
9 verbose stack     at FSReqCallback.oncomplete (node:fs:196:5)
10 verbose cwd /home/akalanka
11 verbose Linux 5.15.133.1-microsoft-standard-WSL2
12 verbose argv "/home/akalanka/.nvm/versions/node/v19.9.0/bin/node" "/home/akalanka/.nvm/versions/node/v19.9.0/lib/node_modules/npx/node_modules/npm/bin/npm-cli.js" "install" "@puppeteer/browsers@latest" "--global" "--prefix" "/home/akalanka/.npm/_npx/5741" "--loglevel" "error" "--json"
13 verbose node v19.9.0
14 verbose npm  v5.1.0
15 error cb.apply is not a function
16 verbose exit [ 1, true ]
```

**Comment by akalankasakalasooriya** [comment]
same happened with docker

```
------
 => ERROR [ 7/15] RUN npx @puppeteer/browsers install chrome@stable                                                                                                                    1.7s
------
 > [ 7/15] RUN npx @puppeteer/browsers install chrome@stable:
1.606 npm ERR! cb.apply is not a function
1.618
1.618 npm ERR! A complete log of this run can be found in:
1.618 npm ERR!     /root/.npm/_logs/2023-11-24T16_53_12_383Z-debug.log
1.666 Install for [ '@puppeteer/browsers@latest' ] failed with code 1
------
Dockerfile:26
--------------------
  24 |     # install chrome tests
  25 |     #RUN npx --yes @puppeteer/browsers install chrome@114.0.5735
  26 | >>> RUN npx @puppeteer/browsers install chrome@stable
  27 |     # install google chrome
  28 |     #RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
--------------------
ERROR: failed to solve: process "/bin/sh -c npx @puppeteer/browsers install chrome@stable" did not complete successfully: exit code: 1
```

**Comment by OrKoN** [comment]
Interesting, it does not look like it's coming @puppeteer/browsers but rather from npm. Could you try a different npm version?  It seems to work with node 20 and npm 9.8.0

**Comment by OrKoN** [comment]
Also for me npx and npm versions match, could it be a mismatch in versions?

**Comment by OrKoN** [comment]
Also, the log prints a different npm version: `verbose npm  v5.1.0`. So it does not sound like it is actionable for us and sounds like a bug/version mismatch in npm.
