### ISSUE TITLE
TS2309: An export assignment cannot be used in a module with other exported elements.

### ISSUE THREAD

**Issue by NikitaZelenskis** [puppeteer/puppeteer#6852]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.0.4
* Platform / OS version: Windows 10
* Node.js version: v14.15.4

**What steps will reproduce the problem?**
This started happening after updating from 7.0.1 to 7.0.4
1.
`tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "outDir": "dist",
    "sourceMap": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true
  }
}
```
`main.ts`:
```
import puppeteer from 'puppeteer';

(async () => {
  puppeteer.launch();
})();

```
2. run
```
tsc -p tsconfig.json
```

**What is the expected result?**
Project should compile

**What happens instead?**

node_modules/puppeteer/lib/types.d.ts:24385:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

**Comment by thomaschaaf** [comment]
It does not occur with 7.0.3

**Comment by hirebarend** [comment]
Having the same issue on my side with a similar configuration.

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "noImplicitAny": false,
    "outDir": "dist",
    "preserveConstEnums": true,
    "removeComments": true,
    "sourceMap": true,
    "target": "es6"
  },
  "include": ["./src/**/*", "./tests/**/*"]
}
```

**Comment by SimonHessel** [comment]
Hey @NikitaZelenskis,
don't know if that's good enough, but I fixed this by just replacing
`export = puppeteer;` with `export default puppeteer;`
Hopes this helps for the time beeing.

**Comment by hirebarend** [comment]
@SimonHessel This fix will only work locally. When using the package in a Docker container, the build still fails.

**Comment by tdodgehdai** [comment]
I'm having this issue too. Using @SimonHessel 's fix for now.

**Comment by nikolasrist** [comment]
We run it in docker container - so the fix would be great!

**Comment by jackfranklin** [comment]
Hey all,

I have learned a lot about shipping TS this week and we _think_ v7.1.0 which shipped today fixes this. It no longer uses `export =` or `export default` in an attempt to be compat with your environment, regardless of if it's ESM or CJS that you're working with.

We also now automatically test our TS types against a tonne of environments: https://github.com/puppeteer/puppeteer/tree/main/test-ts-types, some use ESM, some CJS, etc, to try to avoid issues like this in the future.

I'm going to close this as I think 7.1.0 fixes it, but please open issues if you have problems, and I'm sorry for the churn and problems we've hit so far on this.
