### ISSUE TITLE
setRequestInterceptionEnabled is not a function?

### ISSUE THREAD

**Issue by Linux999** [puppeteer/puppeteer#1431]
after updating from puppeteer 0.12.0 to 0.13.0 today, I got the following error message:

TypeError: page.setRequestInterceptionEnabled is not a function

After going back to 0.12.0, everything worked fine.

Is there a change in code? Why is it not working anymore?

Code:
await page.setRequestInterceptionEnabled(true);						
await page.goto(curl, { waitUntil: 'networkidle', timeout: 1500000 });

**Comment by ebidel** [comment]
It was renamed in https://github.com/GoogleChrome/puppeteer/releases/tag/v0.13.0.

`page. setRequestInterception`
