### ISSUE TITLE
Typings issues with version 8.0.0 -  Cannot find name 'Lowercase'

### ISSUE THREAD

**Issue by julien-sarazin** [puppeteer/puppeteer#6934]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 8.0.0
* Platform / OS version: Mac OS Big Sur
* Node.js version: 12.20.1

**What steps will reproduce the problem?**
- Install, `npm i (with the 8.0.0 version)`
- Build, `npm run build`

**What is the expected result?**
Project build successfully 

**What happens instead?**
Typings issues :
```
node_modules/puppeteer/lib/types.d.ts:24083:36 - error TS2304: Cannot find name 'Lowercase'.
```

**Comment by julien-sarazin** [comment]
When I target the issue in the`types.d.ts` file, my IDE redirects me on a `lib.es5.s.ts` typings. I tried to add the `"ES5"` on the extra `lib` tsconfig options but it does not help.

**Comment by superzadeh** [comment]
Just ran into the same issue on our CI after upgrading to 8.0.0. Rolled back to 7.1.0, and don't have the issue anymore.

**Comment by julien-sarazin** [comment]
I confirm the 7.1.0 does not trigger the issue. (Typescript 3.9.7)

**Comment by weicheng95** [comment]
Puppeteer just release breaking changes on v.8.0.0.
https://pptr.dev/#?product=Puppeteer&version=v8.0.0&show=api-release-notes
To fix that, downgrade to v7.1.0 for now.

**Comment by adam-s** [comment]
I have the same issue using TypeScript 4.3.0-dev.20210223. Do you think this might be a TypeScript bug more than a Puppeteer bug?

**Comment by julien-sarazin** [comment]
> I have the same issue using TypeScript 4.3.0-dev.20210223. Do you think this might be a TypeScript bug more than a Puppeteer bug?

Using Typescript 3.9.7 as mentioned above. Same issue. At some point, it has "compiled with a version of typescript "

**Comment by Nighthawk14** [comment]
Anyone managed to fix that issue?

I just created a definition file that I added to my tsconfig.json including:
```
type Lowercase<S extends string> = string;
```

And that fixed it for now. Not ideal though.

**Comment by julien-sarazin** [comment]
Still using the 7.1.0. But thanks for the workaround 👍

**Comment by SPodjasek** [comment]
`Lowercase<T>` was introduced with TypeScript 4.1, so using any version newer then that should fix this problem.

**Comment by SPodjasek** [comment]
> I have the same issue using TypeScript 4.3.0-dev.20210223. Do you think this might be a TypeScript bug more than a Puppeteer bug?

@adam-s  Check your global `tsc --version` - in my case I've had an old v3.9, so running `tsc` from command line would fail, while `yarn build`/`npm run build` would work. Now, both work at version 4.2.3.

**Comment by julien-sarazin** [comment]
@SPodjasek Thanks, I'll give it a try ASAP and confirm the solution.

**Comment by dbryar** [comment]
Confirmed updating Typescript from v3.9.x to ^4.0 resolves this issue 
`npm i -D typescript@^4.0`

I would suggest updating the package dependencies to suit

**Comment by rhuanbarreto** [comment]
Updating typescript solve the problem.

Thanks @dbryar !

**Comment by julien-sarazin** [comment]
I confirm upgrading typescript to 4.2.4 works. Closing the issue. Thanks all.

**Comment by Alex-2kZharkov** [comment]
Had the same issue. I upgraded the typescript from 3.9 to 4.1 and it solved the problem.
Thanks to @dbryar

**Comment by filipgorny** [comment]
Updated typescript to 4.4.4 - didn't fix the problem.
