### ISSUE TITLE
[Bug]: 21.2.1 throws Cannot find name 'AsyncDisposable'. error on tsc --build.

### ISSUE THREAD

**Issue by nk-reichenbach-fall** [puppeteer/puppeteer#10908]
### Minimal, reproducible example

```TypeScript
import mdToPdf from 'md-to-pdf';

const pdfData = await mdToPdf(
      {
        content: 'I love *markdowns*',
      },
  {
    pdf_options: {
      format: 'A4',
      printBackground: true,
      margin: { top: '35mm', bottom: '20mm', left: '10mm', right: '10mm' }
    }
  })
```

### Error string

node_modules/puppeteer/lib/types.d.ts:209:62 - error TS2304: Cannot find name 'AsyncDisposable'.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

I am using [md-to-pdf](https://github.com/simonhaenisch/md-to-pdf) tool to convert markdown to pdf. The md-to-pdf uses puppeteer to convert html to pdf. Everything worked fine up until 2 days back. With the new version of puppeteer (21.2.1), i am getting error while building the application. 

node - 16.20.0
typescript - 4.8.2
@types/node - 16.11.56
md-to-pdf - 5.2.4

The error message is 
```
node_modules/puppeteer/lib/types.d.ts:209:62 - error TS2304: Cannot find name 'AsyncDisposable'.

209 export declare class Browser extends EventEmitter implements AsyncDisposable, Disposable {
                                                                 ~~~~~~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:209:79 - error TS2304: Cannot find name 'Disposable'.

209 export declare class Browser extends EventEmitter implements AsyncDisposable, Disposable {
                                                                                  ~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:344:5 - error TS1165: A computed property name in an ambient context must refer to an expression whose type is a literal type or a 'unique symbol' type.

344     [Symbol_2.dispose](): void;
        ~~~~~~~~~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:344:15 - error TS2339: Property 'dispose' does not exist on type 'SymbolConstructor'.

344     [Symbol_2.dispose](): void;
                  ~~~~~~~

node_modules/puppeteer/lib/types.d.ts:345:5 - error TS1165: A computed property name in an ambient context must refer to an expression whose type is a literal type or a 'unique symbol' type.

345     [Symbol_2.asyncDispose](): Promise<void>;
        ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:345:15 - error TS2339: Property 'asyncDispose' does not exist on type 'SymbolConstructor'.

345     [Symbol_2.asyncDispose](): Promise<void>;
                  ~~~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:3280:64 - error TS2304: Cannot find name 'Disposable'.

3280 export declare abstract class JSHandle<T = unknown> implements Disposable, AsyncDisposable, Moveable {
                                                                    ~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:3280:76 - error TS2304: Cannot find name 'AsyncDisposable'.

3280 export declare abstract class JSHandle<T = unknown> implements Disposable, AsyncDisposable, Moveable {
                                                                                ~~~~~~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:3354:5 - error TS1165: A computed property name in an ambient context must refer to an expression whose type is a literal type or a 'unique symbol' type.

3354     [Symbol_2.dispose](): void;
         ~~~~~~~~~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:3354:15 - error TS2339: Property 'dispose' does not exist on type 'SymbolConstructor'.

3354     [Symbol_2.dispose](): void;
                   ~~~~~~~

node_modules/puppeteer/lib/types.d.ts:3355:5 - error TS1165: A computed property name in an ambient context must refer to an expression whose type is a literal type or a 'unique symbol' type.

3355     [Symbol_2.asyncDispose](): Promise<void>;
         ~~~~~~~~~~~~~~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:3355:15 - error TS2339: Property 'asyncDispose' does not exist on type 'SymbolConstructor'.

3355     [Symbol_2.asyncDispose](): Promise<void>;
                   ~~~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:4218:68 - error TS2304: Cannot find name 'AsyncDisposable'.

4218 export declare abstract class Page extends EventEmitter implements AsyncDisposable, Disposable {
                                                                        ~~~~~~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:4218:85 - error TS2304: Cannot find name 'Disposable'.

4218 export declare abstract class Page extends EventEmitter implements AsyncDisposable, Disposable {
                                                                                         ~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:5970:5 - error TS1165: A computed property name in an ambient context must refer to an expression whose type is a literal type or a 'unique symbol' type.

5970     [Symbol.dispose](): void;
         ~~~~~~~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:5970:13 - error TS2339: Property 'dispose' does not exist on type 'SymbolConstructor'.

5970     [Symbol.dispose](): void;
                 ~~~~~~~

node_modules/puppeteer/lib/types.d.ts:5971:5 - error TS1165: A computed property name in an ambient context must refer to an expression whose type is a literal type or a 'unique symbol' type.

5971     [Symbol.asyncDispose](): Promise<void>;
         ~~~~~~~~~~~~~~~~~~~~~

node_modules/puppeteer/lib/types.d.ts:5971:13 - error TS2339: Property 'asyncDispose' does not exist on type 'SymbolConstructor'.

5971     [Symbol.asyncDispose](): Promise<void>;
```
### Expectation

It was working with 21.1.1

### Reality

With new update, build fails. 

### Puppeteer version

21.2.1

### Node version

16.20.0

### Package manager

npm

### Package manager version

8.19.4

### Operating system

macOS

**Comment by jrandolf** [comment]
Thanks for the bug report! It seems our API extractor didn't extract those symbols (https://github.com/microsoft/rushstack/issues/1709).

While we work on fixing this, you can use `skipLibCheck` to ignore the error. This shouldn't affect type checking capabilities in your code.
