### ISSUE TITLE
[Bug]: TypeScript private fields do not work when target is es5

### ISSUE THREAD

**Issue by cascornelissen** [puppeteer/puppeteer#8537]
### Bug description

Steps to reproduce the problem:

1. Set `target` to `es5` in `tsconfig.json`
1. Run something like `tsc --declaration --emitDeclarationOnly`

This works on `14.3.0` but breaks on `14.4.0`, the relevant changes were made in #8506. I couldn't really find anything related to whether it's ok that this broke according to the guidelines but it was unexpected to use, which is why I'm creating this issue.

### Puppeteer version

14.4.0

### Node.js version

v16.13.1

### npm version

8.9.0

### What operating system are you seeing the problem on?

macOS

### Relevant log output

```shell
node_modules/puppeteer/lib/types.d.ts:6999:14 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

6999              #private;
                  ~~~~~~~~
```

**Comment by jrandolf-google** [comment]
Is there a reason you need to use `es5`?

**Comment by cascornelissen** [comment]
It pains me to say it out loud but we still support Internet Explorer (for a few more weeks). Puppeteer doesn't have anything to do with the fact that we're still supporting this ancient browser, I just created this issue because it was kind of unexpected that our builds started failing with this new minor version of puppeteer.

I'm ok with not fixing this on puppeteer's side by the way, just wanted to make clear that this is happening to us and probably to others as well.

**Comment by jrandolf-google** [comment]
I see. I'd recommend somehow separating the testing infrastructure from your builds. Puppeteer is in no way related to IE, so it'd be best to keep these separate build-wise.
