### ISSUE TITLE
Cannot find module 'puppeteer-core/internal/puppeteer-core.js' after upgrading to Puppeteer 24.x.x

### ISSUE THREAD

**Issue by mrinalkopulwar** [puppeteer/puppeteer#13988]
Hi team,

I'm facing an issue after upgrading Puppeteer from v2.1.0 to v24.8.2.

After the upgrade, I get the following runtime error:
Error: Cannot find module 'puppeteer-core/internal/puppeteer-core.js'

Node.js: [v20.19.2]
Puppeteer: 24.8.2
Installed with: npm install puppeteer@24.8.2

After installing, I notice both puppeteer and puppeteer-core folders exist under node_modules, which I understand is expected.

However, the puppeteer package imports files from puppeteer-core/internal/..., and those references seem to break during runtime. The error suggests the module is missing or not bundled correctly.

Sample Code:
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await browser.close();
})();

Error ScreenShot:
![Image](https://github.com/user-attachments/assets/37ed3fc0-bd0a-449b-85b0-354430653df7)

Puppeteer core import path is wrong under the files present in puppeteer folder.
<img width="949" alt="Image" src="https://github.com/user-attachments/assets/14ffbc49-d6f8-40d3-b5e4-9d86c476ddc5" />

**Comment by OrKoN** [comment]
I am not able to reproduce but it looks like an outdated Node.js version is used that cannot handle the modern import syntax in package.json.
