### ISSUE TITLE
[Bug]: v21.2.0 Incompatible with `@types/node@18`

### ISSUE THREAD

**Issue by rwaskiewicz** [puppeteer/puppeteer#10891]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer"; 

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://example.com');
  const hrefElement = await page.$('a');
  if (hrefElement) {
      await hrefElement.click();
  }
  // ...
})();
```

### Error string

node_modules/puppeteer/lib/types.d.ts:5971:13 - error TS2339: Property 'asyncDispose' does not exist on type 'SymbolConstructor'.

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Background

When working in a TypeScript (5.1, 5.2) environment with `@types/node@18`, I began to see this error when trying to compile using today's release of Puppeteer (21.2.0). After fiddling with `@types/node` versions, I was able to see that this error occurs for the latest typings of Node 18 (18.17.15), but does not for Node 20 (20.6.0).

I am able to run Puppeteer successfully with the following environment:
- TypeScript v5.1 or v5.2
- Puppeteer v21.1.1
- `@types/node` v18.17.5

It is upon upgrading Puppeteer to v21.2.20 that I begin to see the error

### Expectation

My current understanding is that Puppeteer supports the latest LTS version of Node, which at the time of this writing is Node 18. I would expect to be able to upgrade Puppeteer with my current environment and not run into any compile time issues.

However, that's predicated on the assumption my understanding of Node support (and its associated types is correct). Please let me know if that's not the case!

### Reality

In reality, we get those compile time issues.

### Puppeteer version

21.2.0

### Node version

18.17.1

### Package manager

npm

### Package manager version

9.6.7

### Operating system

macOS

**Comment by jrandolf** [comment]
This usually occurs with `skipLibCheck: false`. It looks like `Disposable` and `AsyncDisposable` are only available on the latest `Node` types or if you set change your typescript "target" to `ESNext`.

We'll fix this in another patch release.
